"""Work on fixing bugs

Revision ID: 4482a086f970
Revises: 288da35a8768
Create Date: 2024-10-29 23:40:56.335958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4482a086f970'
down_revision = '288da35a8768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('attendance_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_class', schema=None) as batch_op:
        batch_op.drop_constraint('student_class_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_class_ibfk_2', 'student', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendance_ibfk_2', 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###
