"""Make end time nullable

Revision ID: 4e4a0a7baad9
Revises: 4482a086f970
Create Date: 2024-11-04 19:14:35.195106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e4a0a7baad9'
down_revision = '4482a086f970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
